title: OCTOChti
email: chti@octo.com
description: >
    OCTOChti website
baseurl: ''
url: 'https://chti.octo.com'
twitter: 'https://twitter.com/octochti'

markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
exclude:
    - Gemfile
    - Gemfile.lock
