title: OCTO chti
email: chti@octo.com
description: |
    OCTO chti website
baseurl: ''
url: 'https://chti.octo.com'
twitter: 'https://twitter.com/octochti'
google_analytics: UA-134710918-1

markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
exclude:
    - Gemfile
    - Gemfile.lock
