name: learn-github-actions
on: [push]
jobs:
  create-web-pictures-for-people:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update; sudo apt-get install webp -y
      - run: for file in assets/images/people/*; do cwebp -resize 1000 0 -q 75 "$file" -o "${file%.*}.webp"; done
