name: learn-github-actions
on: [push]
jobs:
  create-web-pictures-for-people:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@master"
      - name: install webp
        run: sudo apt-get update; sudo apt-get install webp -y
      - name: convert png to webp format
        run: bash ./.github/convert_png_pictures_to_webp.sh
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          message: 'Conversion of new octo pictures to webp format'

